FROM golang:1.13 as builder

WORKDIR /build

COPY go.mod go.sum /build/
RUN go mod download

COPY . .
RUN go test ./...
RUN go build ./cmd/salus-packages-agent.go

FROM ubuntu:18.04

COPY --from=builder /build/salus-packages-agent /usr/bin/
RUN /usr/bin/salus-packages-agent
RUN /usr/bin/salus-packages-agent --line-protocol-to-console