version: '3'

services:
  sut:
    depends_on:
      - telegraf
    build:
      context: .
    volumes:
    - ./testdata/compose-configs:/configs
    command: --configs /configs --line-protocol-to-socket telegraf:8094 --debug
  telegraf:
    image: telegraf:1.13
    ports:
      - 8094:8094
    volumes:
      - ./testdata/telegraf.conf:/etc/telegraf/telegraf.conf:ro
